// Keep the combined height of tabBarIconSize  + tabBarLabelFontSize <= 32 to avoid clipping
export const themes = {
  light: {
    statusBarStyle: "light",
    background: '#faf9f7',
    cardBackground: '#ffffff',
    inputBackground: '#ffffff',
    skeletonBackground: '#f8f6f4',
    headerBackground: '#ffffff',
    tabBarBackground: '#ffffff',
    tabBarActiveIcon: '#f2a41e',
    tabBarInactiveIcon: '#a8a29e',
    tabBarActiveLabel: '#f2a41e',
    tabBarInactiveLabel: '#a8a29e',
    tabBarBorder: '#f5f5f4',
    tabBarBorderTopWidth: 0,
    tabBarIconSize: 20,
    tabBarLabelFontSize: 12,
    text: '#1c1917',
    textMuted: '#78716c',
    textLight: '#a8a29e',
    primary: '#f2a41e',
    primaryForeground: '#ffffff',
    secondary: '#f2a41e',
    secondaryForeground: '#ffffff',
    success: '#65a30d',
    successForeground: '#ffffff',
    destructive: '#dc2626',
    destructiveForeground: '#ffffff',
    warning: '#ea580c',
    warningForeground: '#ffffff',
    border: '#e7e5e4',
    borderLight: '#f5f5f4',
    cardShadowColor: '#000',
    cardShadowOpacity: 0.08,
    cardShadowRadius: 6,
    cardElevation: 3,
    skeletonAnimationStart: '#f8f6f4',
    skeletonAnimationEnd: '#e7e5e4',
    borderRadius: 12,  // Default card/button border radius
    accent: '#f2a41e',
    accentForeground: '#1c1917',
    muted: '#f5f5f4',
    mutedForeground: '#78716c',
    wellness: '#a7c4bc',
    wellnessForeground: '#ffffff',
    nurturing: '#f4e4d6',
    nurturingForeground: '#1c1917',
    feedback: {
      positive: '#10b981',
      neutral: '#f59e0b',
      negative: '#ef4444',
    },
    glassmorphic: {
      background: 'rgba(255, 255, 255, 0.85)',
      border: 'rgba(255, 255, 255, 0.2)',
      isDark: false,
    },
  },
  dark: {
    statusBarStyle: "dark",
    background: '#0A0A0A',
    cardBackground: '#1A1A1A',
    inputBackground: '#1A1A1A',
    skeletonBackground: '#1A1A1A',
    headerBackground: '#0F0F0F',
    tabBarBackground: '#0F0F0F',
    tabBarActiveIcon: '#f2a41e',
    tabBarInactiveIcon: '#78716c',
    tabBarActiveLabel: '#f2a41e',
    tabBarInactiveLabel: '#78716c',
    tabBarBorder: '#3f3f46',
    tabBarBorderTopWidth: 0,
    tabBarIconSize: 20,
    tabBarLabelFontSize: 12,
    text: '#fafaf9',
    textMuted: '#a8a29e',
    textLight: '#78716c',
    primary: '#f2a41e',
    primaryForeground: '#ffffff',
    secondary: '#f2a41e',
    secondaryForeground: '#ffffff',
    success: '#84cc16',
    successForeground: '#1c1917',
    destructive: '#ef4444',
    destructiveForeground: '#ffffff',
    warning: '#f97316',
    warningForeground: '#ffffff',
    border: '#3f3f46',
    borderLight: '#52525b',
    cardShadowColor: '#000',
    cardShadowOpacity: 0.3,
    cardShadowRadius: 6,
    cardElevation: 3,
    skeletonAnimationStart: '#292524',
    skeletonAnimationEnd: '#3f3f46',
    borderRadius: 12,  // Default card/button border radius
    accent: '#f2a41e',
    accentForeground: '#fafaf9',
    muted: '#3f3f46',
    mutedForeground: '#a8a29e',
    wellness: '#7c9885',
    wellnessForeground: '#fafaf9',
    nurturing: '#44403c',
    nurturingForeground: '#fafaf9',
    feedback: {
      positive: '#10b981',
      neutral: '#f59e0b',
      negative: '#ef4444',
    },
    glassmorphic: {
      background: 'rgba(26, 26, 26, 0.85)',
      border: 'rgba(255, 255, 255, 0.1)',
      isDark: true,
    },
  }
} as const;

export const DEFAULT_THEME_IN_CONTEXT = "dark";
// Default theme for backward compatibility
export const defaultTheme = themes[DEFAULT_THEME_IN_CONTEXT];